# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: JasonLovesDoggo
          template: classic
          base: header, activity, community, repositories, metadata
          commits_authoring: JasonLovesDoggo, JakeWasChosen, git@jasoncameron.dev, jason@jasoncameron.dev
          config_display: columns
          config_octicon: yes
          config_timezone: America/Toronto
          # plugin_activity: yes
          # plugin_activity_days: 14
          # plugin_activity_filter: all
          # plugin_activity_limit: 5
          # plugin_activity_load: 300
          # plugin_activity_timestamps: yes
          # plugin_activity_visibility: all
          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_analysis_timeout_repositories: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: bytes-sized
          plugin_languages_ignored: HTML, Less, SCSS, TypeScript, Processing, EJS
          plugin_languages_indepth: yes
          plugin_languages_limit: 10
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 100
          plugin_languages_sections: most-used, 
          plugin_lines: yes
          plugin_lines_delay: 3
          plugin_lines_history_limit: 5
          plugin_lines_repositories_limit: 10
          plugin_lines_sections: base
          plugin_notable: yes
          plugin_notable_filter: stars:>20
          plugin_notable_from: all
          plugin_notable_repositories: yes
          plugin_notable_self: yes
          plugin_notable_types: commit, pull_request
          # plugin_people: yes
          # plugin_people_identicons_hide: yes
          # plugin_people_limit: 24
          # plugin_people_shuffle: yes
          # plugin_people_size: 24
          # plugin_people_types: followers, following
